language: ruby
rvm:
- 2.3.1
install: bundle install
before_script:
- openssl aes-256-cbc -K $encrypted_a2eebb89a5a7_key -iv $encrypted_a2eebb89a5a7_iv -in .travisdeploykey.enc -out .travisdeploykey -d
- chmod go-rwx .travisdeploykey
- eval `ssh-agent -s`
- ssh-add .travisdeploykey
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
- COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n
  1 --format='commit %h - %s'`"
script:
- rake cibuild
- set -e
- rake build
- git checkout --orphan gh-pages
- echo "isaackuek.me" > _site/CNAME
- git add -f _site/
- git commit -m "${COMMIT_MESSAGE}"
- git filter-branch -f --subdirectory-filter _site/
- git push -f https://$GH_TOKEN@github.com/isaackuek/isaackuek.me.git gh-pages:gh-pages
branches:
  only:
  - master
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
